### ISSUE TITLE
MkBucket.list() must show directories

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-s3#12]
`MkBucket.list()` must show directories, not only files

**Comment by dmarkov** [comment]
@yegor256 right, I added the `bug` tag

**Comment by dmarkov** [comment]
I will find a developer for the task soon...

**Comment by dmarkov** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-a58ac766

**Comment by dmarkov** [comment]
@super132 it's yours, please go ahead

**Comment by super132** [comment]
@yegor256 PR #30 fixed this issue. Would you please close this ticket? Thanks.

**Comment by yegor256** [comment]
@super132 thanks!

**Comment by dmarkov** [comment]
@super132 thanks, I just added **30 mins** to your account, payment `AP-8LR27509N4899350T`, 144 hours and 3 mins spent. +30 to your rating, your total score is [+211](http://www.netbout.com/b/35282?open=rating)
