### ISSUE TITLE
Incomplete documentation of Prefixed class

### ISSUE THREAD

**Issue by darkled** [jcabi/jcabi-s3#14]
The documentation says nothing about what for the class `com.jcabi.s3.Bucket.Prefixed` exists. I would suggest to complete the javadoc for the class.

**Comment by dmarkov** [comment]
we'll find someone to do this task, soon

**Comment by dmarkov** [comment]
@apocarteres please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by dmarkov** [comment]
@darkled thanks for reporting! I topped your account for 15 mins, transaction 49720012

**Comment by dmarkov** [comment]
@apocarteres you're holding this task for 11 days already... -30 added to your rating, current score is: [+0](http://www.netbout.com/b/35111?open=rating)

**Comment by apocarteres** [comment]
added some JavaDoc. can you merge it pls?

**Comment by darkled** [comment]
@apocarteres you need to create a pull request at first. And the javadoc in dda836cb82c70ad4730b2725215cd229d9ebaf31 still does not explain what `prefix` is and why it is needed.

**Comment by apocarteres** [comment]
@darkled updated JavaDoc for prefix field. check it out in my PR. Is it clearer now?

**Comment by darkled** [comment]
@apocarteres I think, the field `prefix` does not need extended documentation since it is pretty self-explained, but the javadoc for the class `Prefixed` should answer the following main questions:
1. Why is this class needed?
2. What does it perform decorating `Bucket` instances?

**Comment by apocarteres** [comment]
i'm sorry. It's quite obvious for me what <code>Prefixed</code> class does do. It's also clear that it uses <code>prefix</code> field to do it's logic, so i clarified with JavaDoc comment on <code>prefix</code> field to be more confident why that's where. If not's enough, i can't help you with this task anymore. 

@dmarkov pls find someone else to get this issue done.

**Comment by apocarteres** [comment]
@darkled Please check last PR

**Comment by dmarkov** [comment]
@apocarteres you were holding this task for too long, it's not yours any more, please stop

-60 added to your rating, at the moment it is: [+15](http://www.netbout.com/b/35111?open=rating)

**Comment by dmarkov** [comment]
@maurezen the issue is yours, please help

**Comment by maurezen** [comment]
@dmarkov created a pull request #23

**Comment by maurezen** [comment]
@darkled pull request #23 merged to master, please close the issue.

**Comment by darkled** [comment]
@maurezen looks nice, thanks!

**Comment by maurezen** [comment]
@dmarkov the task is already closed.

**Comment by maurezen** [comment]
@dmarkov @yegor256  the task was closed 5 days ago.

**Comment by dmarkov** [comment]
@maurezen **30 mins** added to your account (payment number `51519684`), many thanks for your contribution!. +30 added to your rating, at the moment it is: [+1095](http://www.netbout.com/b/35102?open=rating)
