### ISSUE TITLE
MkBucketTest.listsOckets fails locally

### ISSUE THREAD

**Issue by darkled** [jcabi/jcabi-s3#16]
Running `mvn clean install` locally on windows machine leads to the result:
```
Failed tests:
  MkBucketTest.listsOckets:68
Expected: (an iterable with size <2> and a collection containing "hello.txt" and a collection containing "f/2.txt")
     but: a collection containing "f/2.txt" was "f\2.txt", was "hello.txt"
```
It seems that path delimiters there are OS dependent.

**Comment by dmarkov** [comment]
I'll find a developer for the task soon...

**Comment by dmarkov** [comment]
@php-coder could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here

Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by dmarkov** [comment]
@php-coder this ticket is not yours any more, thanks

**Comment by dmarkov** [comment]
@darkled many thanks for the report, I topped your account for 15 mins, transaction 49762717

**Comment by dmarkov** [comment]
@adko-pl the task is yours

**Comment by adko-pl** [comment]
@dmarkov changes delivered in https://github.com/jcabi/jcabi-s3/pull/20

**Comment by darkled** [comment]
@adko-pl it's working now, thanks!

**Comment by dmarkov** [comment]
@adko-pl thank you, added **30 mins** to your acc, payment num is `AP-6YA29884FW533194K`... +30 to your rating, your total score is +125
