### ISSUE TITLE
MkOcket should return some meaningful ObjectMetadata

### ISSUE THREAD

**Issue by carlosmiranda** [jcabi/jcabi-s3#25]
Right now, `MkOcket.meta()` just returns a new instance of `ObjectMetadata`. However, it would be useful for `ObjectMetadata` to return some meaningful (and commonly used) data.

For example, `contentLength` would be useful when I need to test a class which needs to get the total size of a bucket (like in https://github.com/teamed/nerodesk/issues/131). I suggest we start with adding `contentLength` and identify other data that might be of use for projects that test with `MkOcket`.

**Comment by dmarkov** [comment]
I will ask someone to take care of this task soon

**Comment by dmarkov** [comment]
@maurezen it's yours, please help, budget is 30 mins

**Comment by dmarkov** [comment]
@carlosmiranda thank you for reporting this, I added 15 mins to your acc, transaction `54208972`

**Comment by maurezen** [comment]
@dmarkov please assign another developer to this task.

**Comment by yegor256** [comment]
@dmarkov assign someone else pls

**Comment by dmarkov** [comment]
> @dmarkov please assign another developer to this task.

@maurezen no problem, I will try to find somebody else

**Comment by dmarkov** [comment]
> @dmarkov assign someone else pls

@yegor256 no problem, I will try to find somebody else

**Comment by longtimeago** [comment]
@yegor256 can we dispatch the issue? It's a blocker for another one

**Comment by dmarkov** [comment]
@longtimeago it's your task now, go ahead

**Comment by longtimeago** [comment]
@yegor256 sorry, but as I said several days ago, I'm on business trip from 29 Apr to 13 May.
So, please, reassign the task to somebody else. Thank you

**Comment by yegor256** [comment]
@dmarkov assign this to someone else pls

**Comment by dmarkov** [comment]
> @dmarkov assign this to someone else pls

@yegor256 30 points deducted from your rating

**Comment by dmarkov** [comment]
> @dmarkov assign this to someone else pls

@yegor256 all right, we'll find someone else for this task

**Comment by dmarkov** [comment]
@yamstranger it's your task, go ahead

**Comment by dmzaytsev** [comment]
@yamstranger please implement also these attributes: `ContentType` and `Date`

**Comment by YamStranger** [comment]
@dmarkov assign to someone else. Sorry.  It seems I was in @away mode when this task was assigned. @yegor256 can you check it please? Thanks.

**Comment by dmarkov** [comment]
> @dmarkov assign to someone else. Sorry.  It seems I was in @away mode when this task was assigned. @yegor256 can you check it please? Thanks.

@yamstranger deducted 30 from your rating :(

**Comment by dmarkov** [comment]
> @dmarkov assign to someone else. Sorry.  It seems I was in @away mode when this task was assigned. @yegor256 can you check it please? Thanks.

@yamstranger someone else will help in this task, no problem at all

**Comment by dmarkov** [comment]
@prondzyn this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here. This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by prondzyn** [comment]
@dmarkov pull request prepared

**Comment by dmarkov** [comment]
> @dmarkov pull request prepared

@prondzyn thanks, will someone to review it soon

**Comment by prondzyn** [comment]
@dmarkov my changes are merged with [jcabi/jcabi-s3](https://github.com/jcabi/jcabi-s3)

**Comment by carlosmiranda** [comment]
@prondzyn thanks

**Comment by dmarkov** [comment]
@prondzyn paid, thanks, added **30 mins** to your account, payment `AP-78F44551AM6728156`, 143 hours and 21 mins was spent; +30 to your rating, your total score is [+30](http://www.netbout.com/b/35715?open=rating)
