### ISSUE TITLE
Estimate project size

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-s3#26]
There is no estimate in the project yet. We have to create one as explained [here](https://github.com/teamed/est)

**Comment by dmarkov** [comment]
@suseika This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here. Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by Suseika** [comment]
@dmarkov Here is a step from the estimating explanation that I don't understand:

>  First, you break down the entire implementation scope into items, like it's done above, and list them under scope

How exactly am I supposed to find out the items for a project? Should I just summarize my estimation of time required to fix the existing issues? Apart from the issues, the project looks quite done for me, I don't see any "planned features" list (I shouldn't just invent them myself, right?). The readme for est utility and the article and the patent linked from it don't seem to have an explanation, those just assume that a developer knows what needs to be implemented.

**Comment by Suseika** [comment]
@dmarkov Another thing is, how should I deliver the estimation? Should I push the .est file to the project repository? If I should push it to the project repository, is there a specific path it should reside at (root directory, /doc directory, somewhere else)?

**Comment by yegor256** [comment]
@Suseika this may help you as an example: https://github.com/yegor256/netbout/issues/576

**Comment by Suseika** [comment]
@yegor256 Thank you, that was helpful, as well as searching for similar issues in jcabi projects.

**Comment by Suseika** [comment]
@dmarkov #32 closes this, please review it and close this issue if the PR is correct.

**Comment by dmarkov** [comment]
@rultor I will close it myself, once it gets out of our backlog

**Comment by dmarkov** [comment]
@suseika thanks, paid, **30 mins** to your account, payment ID is `AP-9BD96466WY609854Y`, task took 48 hours and 5 mins to complete. +30 to your rating, your total score is [+30](http://www.netbout.com/b/35381?open=rating)

**Comment by dmarkov** [comment]
@yegor256 Closing, thanks all
