### ISSUE TITLE
AwsBucket.java:115-119: Large lists are not supported....

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-s3#3]
Puzzle `2-68b8eec9` in `src/main/java/com/jcabi/s3/AwsBucket.java:115-119` has to be resolved: Large lists are not supported. The method doesn't support marker functionality, provided by ObjectListing. We should create a test that reproduces the problem and fix the method. The method should return an iterable, which should fetch portions of objects from S3 on demand.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@cyberone you're holding this ticket for 13 days already. If it's not finished (and closed) in the next 24 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. do not forget that the ticket will be closed once the `@todo` puzzle is removed from the code, in master branch. -30 added to your rating, current score is: [-160](http://www.netbout.com/b/35076?open=rating)

**Comment by dmarkov** [comment]
@cyberone you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. added -60 to your rating, now it is equal to [-370](http://www.netbout.com/b/35076?open=rating)

**Comment by dmarkov** [comment]
@romankisilenko please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmarkov** [comment]
@romankisilenko just a reminder that you're working with this task for 15 days already. do not forget that you should remove the `@todo` puzzle from the source code. -30 added to your rating, current score is: +420

**Comment by RomanKisilenko** [comment]
@dmarkov PR https://github.com/jcabi/jcabi-s3/pull/21 was reviewed and closed, please close this issue as well.

**Comment by dmarkov** [comment]
@romankisilenko please stop here, the task is not yours any more. -60 to your rating, your total score is +330

**Comment by RomanKisilenko** [comment]
@dmarkov Why the task is not closed and instead I'm penalized? I think there is some kind of error. Could you please close this task and pay for it.

**Comment by yegor256** [comment]
@dmarkov please add extra 30 mins to @RomanKisilenko

**Comment by dmarkov** [comment]
> @dmarkov please add extra 30 mins to @RomanKisilenko 

@yegor256 30 mins extra was just paid to @romankisilenko, transaction `51287967`

**Comment by dmarkov** [comment]
We're done here, thanks all
