### ISSUE TITLE
S3-compatible API's not supported

### ISSUE THREAD

**Issue by Lewiscowles1986** [jcabi/jcabi-s3#45]
S3 is actually supported by non-amazon service providers including `dreamobjects`, ceph (with addons), and riak.

It would be really nice to be able to connect to non-amazon URL's

#### AWS S3 connection using another provider (mDNS avahi entry used)
```java
AWSCredentials credentials = new BasicAWSCredentials(accessKey, secretKey);
AmazonS3 conn = new AmazonS3Client(credentials);
conn.setEndpoint("s3-compatible-url.local");
```

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by Lewiscowles1986** [comment]
I'm interested for now to find if this is something @yegor256 thinks would work with this. I Can write the small one or two line change. What I would be concerned about is the implications for the framework to incorporate.

**Comment by yegor256** [comment]
@Lewiscowles1986 this is a nice idea, thanks for reporting. I will try to implement it soon

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/jcabi/jcabi-s3/issues/45#issuecomment-322222799))

@yegor256 Job `gh:jcabi/jcabi-s3#45` is in scope.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-s3#45` assigned to [@t-izbassar](http://www.0crat.com/u/t-izbassar}). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read [§4](http://datum.zerocracy.com/pages/policy.html#4), [§8](http://datum.zerocracy.com/pages/policy.html#8), and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
[@t-izbassar](http://www.0crat.com/u/t-izbassar) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@t-izbassar[/z](http://www.0crat.com/u/t-izbassar) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) resigned from [#45](https://github.com/jcabi/jcabi-s3/issues/45), please stop working

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by yegor256** [comment]
@Lewiscowles1986 it seems that it should work already, out of the box. Did you try?

**Comment by Lewiscowles1986** [comment]
Yes, it was a very long time ago now 2016, so retry?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/jcabi/jcabi-s3/issues/45#issuecomment-383536177))

@yegor256 GitHub issue is still open, won't close

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by Lewiscowles1986** [comment]
Looks fixed

### Original test

```
    AWSCredentials credentials = new BasicAWSCredentials(accessKey, secret);
    AmazonS3 conn = new AmazonS3Client(credentials);
    conn.setEndpoint("https://objects-us-west-1.dream.io");
```

### Shorter syntax

```
    AmazonS3 conn = getConnection(
      accessKey, secret,
      "https://objects-us-west-1.dream.io"
    );
```

then

```
    List<Bucket> buckets = conn.listBuckets();
    for (Bucket bucket : buckets) {
      System.out.println("%s".format(
        bucket.getName()
      ));
      ObjectListing objects = conn.listObjects(bucket.getName());
      do {
        for (S3ObjectSummary objectSummary : objects.getObjectSummaries()) {
          System.out.printf("%s\t%s\t%s\t%s%n",
            objectSummary.getBucketName(),
            objectSummary.getSize(),
            objectSummary.getLastModified().toString(),
            objectSummary.getKey()
          );
        }
        objects = conn.listNextBatchOfObjects(objects);
      } while (objects.isTruncated());
    }
```

Works just fine. Thanks :+1:

**Comment by Lewiscowles1986** [comment]
Let me know if there is a wiki or docs where you'd like this information, or if you'd like a test

**Comment by 0crat** [comment]
The job [#45](https://github.com/jcabi/jcabi-s3/issues/45) is now out of scope
