### ISSUE TITLE
MkOcket.meta() is not complete

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-s3#47]

**Comment by yegor256** [comment]
@rultor release, tag is `0.13`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13`

**Comment by 0crat** [comment]
Job "gh:jcabi/jcabi-s3#47" is not in scope
