### ISSUE TITLE
pom.xml:160-162: For some reason this profile doesn't wor...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-s3#48]
The puzzle `47-51f62688` in `pom.xml` (lines 160-162) has to be resolved: For some reason this profile doesn't work any more. Most probably because of the absence of Cobertura. Let's configure it properly, so that it works with Jacocco.

The [puzzle](http://www.yegor256.com/2009/03/04/pdd.html) was created by Yegor Bugayenko on 25-Jan-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in

Done, job `gh:jcabi/jcabi-s3#48` is in scope of "C3RUBL5H9"

**Comment by 0pdd** [comment]
The puzzle `47-51f62688` has disappeared from the source code, that's why I closed this issue.
