### ISSUE TITLE
Bucket.exists()

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-s3#5]
Let's add method `Bucket.exists()` to check bucket existence

**Comment by yegor256** [comment]
@darkled when you complete the task, you should inform the reporter of the ticket that it's time to close it, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#2.-close-it!

**Comment by darkled** [comment]
@yegor256 thanks, my fault. Would you mind to close this issue, please?

**Comment by yegor256** [comment]
@darkled sure, thanks!

**Comment by dmarkov** [comment]
@darkled Many thanks! **30 mins** were added to your account in Transaction ID `49997558`... added +30 to your rating, now it is equal to [+45](http://www.netbout.com/b/35091?open=rating)
