### ISSUE TITLE
CdOcket.meta() must be cacheable too

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-s3#53]
`CdOcket.meta()` must be cacheable too.

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/jcabi/jcabi-s3/issues/53#issuecomment-322223016))

@yegor256 Job `gh:jcabi/jcabi-s3#53` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+1710](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.16`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-s3#53` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+1755](http://www.0crat.com/u/yegor256).
