### ISSUE TITLE
FkRegion/FkBucket with default temp dir

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-s3#54]
Let's make it default

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-s3#54` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+2970](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.17`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-s3#54` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+3030](http://www.0crat.com/u/yegor256).
