### ISSUE TITLE
enable custom Amazon S3 client config

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-s3#56]
Let's make it possible

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-s3#56` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+3910](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-s3#56` is already assigned to @yegor256, sorry.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+3925](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-s3#56` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+3955](http://www.0crat.com/u/yegor256).
